//Get Comment
export const GET_ALL_COMMENT_TASK_SAGA = "GET_ALL_COMMENT_TASK_SAGA"
export const GET_ALL_COMMENT_TASK = "GET_ALL_COMMENT_TASK"

//Add 
export const ADD_COMMENT_TASK_SAGA = "ADD_COMMENT_TASK_SAGA"
export const ADD_COMMENT_TASK = "ADD_COMMENT_TASK"

//Edit
export const UPDATE_COMMENT_TASK_SAGA = "UPDATE_COMMENT_TASK_SAGA"
export const UPDATE_COMMENT_TASK = "UPDATE_COMMENT_TASK"

//Delete 
export const DELETE_COMMENT_TASK_SAGA = "DELETE_COMMENT_TASK_SAGA"
export const DELETE_COMMENT_TASK = "DELETE_COMMENT_TASK"


